{{- if .Values.guac.graphqlServer.ports }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.guac.graphqlServer.name }}
  labels:
    {{- include "guac.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.guac.graphqlServer.name }}
    app.kubernetes.io/component: {{ .Values.guac.graphqlServer.name }}
spec:
  selector:
    {{- include "guac.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.guac.graphqlServer.name }}
    app.kubernetes.io/component: {{ .Values.guac.graphqlServer.name }}
  ports:
  {{- range .Values.guac.graphqlServer.ports }}
    - {{ . | toYaml | indent 6 | trim }}
  {{- end }}   
{{- end }} 