
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guac-cm
data:
  guac.yaml: |

    # TO-DO: externalize secrets from CM
    # neo4j
    gdbuser: neo4j
    gdbpass: {{ .Values.neo4j.neo4j.password }}
    gdbaddr: neo4j://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:7687
    realm: neo4j

    # nats
    natsaddr: nats://{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222

    # collect-sub
{{- with (index .Values.guac.collectSub.ports 0) }}
    csub-addr: {{ $.Values.guac.collectSub.name }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ .targetPort }}
    csub-listen-port: {{ .targetPort }}
{{- end }}

    # graphql-server
{{- with (index .Values.guac.graphqlServer.ports 0) }}
    gql-backend: neo4j
    gql-port: {{ .targetPort }}
    gql-debug: false
    gql-endpoint: http://{{ $.Values.guac.graphqlServer.name }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ .targetPort }}/query
{{- end }}