{{- if .Values.guac.deploySecretProviderClass }}

---
kind: SecretProviderClass
apiVersion: secrets-store.csi.x-k8s.io/v1
metadata:
    name: aws-ssm-secrets
    namespace: {{ .Release.Namespace }}
spec:
    provider: aws
    parameters:
        objects: |
            - objectName: /kusari-gh-app/prod/imagepullsecret
              objectAlias: imagepullsecret
              objectType: ssmparameter

    secretObjects:
        - type: kubernetes.io/dockerconfigjson
          secretName: imagepullsecret
          data:
            - key: .dockerconfigjson
              objectName: imagepullsecret

{{- end }}